name: Wanderlust CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - name: Backup .env
      run: |
        if [ -f .env ]; then mv .env ../env_backup; fi

    - uses: actions/checkout@v4

    - name: Restore .env
      run: |
        if [ -f ../env_backup ]; then mv ../env_backup .env; fi

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    
    - name: Restart backend with PM2
      run: |
        pm2 restart backend || pm2 start app.js --name backend
        pm2 save
