
name: Wanderlust CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Backup .env
      run : |
        if [ -f .env ]; then mv .env /tmp/env_backup; fi
    - uses: actions/checkout@v4
    - name: Restore .env
      run : |
       if [ -f /tmp/env_backup ]; then mv /tmp/env_backup .env; fi
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: sudo pm2 restart backend  
    # - run: npm test
